# Introduction


- Chemistry
    - Experiments are expensive and not environmentally friendly
- Computational Chemistry:
    - Simulate and predict chemical reactions using computers to solve equations from quantum chemistry

### Why quantum computing?
- Richard Feynman:
    - "Nature isn’t classical, and if you want to make a simulation of Nature, you’d better make it quantum mechanical"
- Examples:
    - $N_2$ fixation reactions at less harsh conditions than Haber process (~1% of CO2 emitted)
    - Needs multireference methods, but the computational cost of these methods is beyond digital computers

## Quantum computing in chemistry:

### Noisy intermediate-scale quantum (NISQ) era
- Currently, hardware for quantum computing algorithms that can potentially outperform classical computational chemistry is not available
    - Quantum phase-estimation (QPE) algorithm:
        - In theory: we know the molecular Hamiltonian (see below) exactly
        - Hence, can simulate a chemical system directly using a quantum computer
    - But not possible in practical terms with current level of quantum hardware


### Variational Quantum Eigensolver (VQE) approach
- Based on variational theorem (quantum mechanics):
    - Exact energy < Approximate energy
- Define a loss function (electronic energy), and minimise it
    - Combines classical and quantum computing:
        - Classical: Optimizers and molecular integrals
        - Quantum: Represent the electronic wave function
    - 2 main approaches (ansatz):
        - Chemistry-based:
            - Expensive, need to make cheaper
        - Heuristic/Hardware-efficient:
            - Cheaper, but often not as reliable and/or efficient
- On the whole, circuit depth is significantly reduced compared to QPE

## Introduction to Quantum Chemistry

#### Schrodinger equation:

$$
\hat{H} \Psi = E \Psi
$$

For fixed set of nuclear coordinates, the electronic Hamiltonian $\hat{H}$ is

$$
\begin{equation}
\hat{H} = \hat{T}_e + \hat{V}_{nn} + \hat{V}_{ne} + \hat{V}_{ee}
\end{equation}
$$

$$
\begin{align}
\text{where } T &= \text{Kinetic energy} \\
V &= \text{Electrostatic interaction} \\
n, e &= \text{nuclei, electrons}
\end{align}
$$

- One of the main goals in computational quantum chemistry:
    - Solve for $\Psi$ = Electronic wave function
    - Allows us to know everything about our molecule
- Problem: Cannot be solved exactly because of electron-electron repulsion
- Solve approximately instead:
    - Simplify problem using a finite basis set:
        - For atoms: Atomic orbitals
            - Localised Gaussian-type functions (exp$(-ax^2)$) about each atom in a molecule
        - For molecules: Molecular orbitals
            - Linear combination of atomic orbitals (LCAO)
                - e.g. $H_2\text{: } \chi_1 = c_1 \phi_1 + c_2 \phi_2$ and $\chi_2 = c_1 \phi_1 - c_2 \phi_2$
    - Hartree-Fock method:
        - Solve for the LCAO coefficients s.t. the total molecular energy is minimized
        - Then 'fill up' the lowest $N_{\text{e}}$ (= number of electrons) molecular orbitals

#### Second quantization formalism
- Working in the space of molecular orbitals
- Fermionic annihilation/creation operators
    - $\hat{a}_p$/$\hat{a}_p^\dagger$: Annihilate/Create electron in molecular orbital $p$


Electronic Hamiltonian in this formalism:
$$
\hat{H} = \sum_{p, q} h_{pq} \hat{a}_p^\dagger \hat{a}_q
+ \frac{1}{2} \sum_{p, q, r, s} h_{pqrs} \hat{a}_p^\dagger \hat{a}_q^\dagger \hat{a}_r \hat{a}_s
$$

using the molecular integrals, $h_{pq}$ and $h_{pqrs}$

$$
h_{pq} = \int \chi_{p}^{*}(\mathbf{x}) \left( -\frac{\nabla^2}{2} - \sum_{A} \frac{Z_A}{\lvert \mathbf{r} - \mathbf{R}_A \rvert} \right) \chi_{q}(\mathbf{x}) d\mathbf{x}
$$

$$
h_{pqrs} = \int \frac{\chi_{p}^{*}(\mathbf{x}_1) \chi_{q}^{*}(\mathbf{x}_2) \chi_{r}(\mathbf{x}_2) \chi_{s}(\mathbf{x}_1)}{\lvert \mathbf{r}_1 - \mathbf{r}_2 \rvert} d\mathbf{x}_1 d\mathbf{x}_2
$$

The electronic wave function is then just

$$
a_{N_e}^\dagger a_{N_e -1}^\dagger \dots a_{2}^\dagger a_{1}^\dagger \lvert 0 \rangle
$$

where $\lvert 0 \rangle$ is the vacuum state, i.e. a state with no particles

In [1]:
# QChem: Hands-on
# Part 1. Setting up and transforming the Chemistry problem to quantum computing

# Import required modules
import numpy as np

# "OpenFermion is a library for compiling and analyzing quantum algorithms to simulate fermionic systems, 
# including quantum chemistry"
import openfermion

# Molecule class to store the molecular integrals and other relevant quantities
from qibochem.driver.molecule import Molecule

In [2]:
# The molecule of interest can be defined using an .xyz file
h2 = Molecule(xyz_file='h2.xyz')

# Then, run a classical computational chemistry software to obtain the molecular integrals

# From their respective manuals:
# "Psi4 is an open-source suite of ab initio quantum chemistry programs"
# h2.run_psi4()
h2.run_pyscf() # Probably can't get PySCF on a Windows system so easily...

# The one- (oei) and two- (tei) electron integrals are obtained after running the chemistry driver
print("One- electron integrals for H2:")
print(h2.oei)
print()
print("Two- electron integrals for H2:")
print(h2.tei)

converged SCF energy = -1.11734903499028
One- electron integrals for H2:
[[-1.27785301e+00 -2.35922393e-16]
 [-4.44089210e-16 -4.48299696e-01]]

Two- electron integrals for H2:
[[[[6.82389533e-01 8.32667268e-17]
   [1.94289029e-16 1.79000576e-01]]

  [[1.94289029e-16 1.79000576e-01]
   [6.70732778e-01 3.60822483e-16]]]


 [[[8.32667268e-17 6.70732778e-01]
   [1.79000576e-01 1.94289029e-16]]

  [[1.79000576e-01 1.94289029e-16]
   [3.60822483e-16 7.05105632e-01]]]]


In [3]:
# With these integrals, we can form the molecular Hamiltonian (see above) as a sum of creation/annihilation operators
fermionic_hamiltonian = h2.hamiltonian("f") # OpenFermion InteractionOperator
# Convert to an OpenFermion FermionOperator
print(fermionic_hamiltonian)

0.7559674441714287 [] +
-1.277853006156875 [0^ 0] +
0.34119476657602105 [0^ 0^ 0 0] +
0.08950028803070331 [0^ 0^ 2 2] +
0.34119476657602105 [0^ 1^ 1 0] +
0.08950028803070331 [0^ 1^ 3 2] +
0.08950028803070331 [0^ 2^ 0 2] +
0.33536638915437944 [0^ 2^ 2 0] +
0.08950028803070331 [0^ 3^ 1 2] +
0.33536638915437944 [0^ 3^ 3 0] +
0.34119476657602105 [1^ 0^ 0 1] +
0.08950028803070331 [1^ 0^ 2 3] +
-1.277853006156875 [1^ 1] +
0.34119476657602105 [1^ 1^ 1 1] +
0.08950028803070331 [1^ 1^ 3 3] +
0.08950028803070331 [1^ 2^ 0 3] +
0.33536638915437944 [1^ 2^ 2 1] +
0.08950028803070331 [1^ 3^ 1 3] +
0.33536638915437944 [1^ 3^ 3 1] +
0.3353663891543795 [2^ 0^ 0 2] +
0.08950028803070331 [2^ 0^ 2 0] +
0.3353663891543795 [2^ 1^ 1 2] +
0.08950028803070331 [2^ 1^ 3 0] +
-0.448299696101638 [2^ 2] +
0.08950028803070331 [2^ 2^ 0 0] +
0.35255281608639233 [2^ 2^ 2 2] +
0.08950028803070331 [2^ 3^ 1 0] +
0.35255281608639233 [2^ 3^ 3 2] +
0.3353663891543795 [3^ 0^ 0 3] +
0.08950028803070331 [3^ 0^ 2 1] +
0.335366389

In [4]:
qubit_hamiltonian = h2.hamiltonian("q")
print(qubit_hamiltonian)

-0.042078976477821856 [] +
-0.044750144015351656 [X0 X1 Y2 Y3] +
0.044750144015351656 [X0 Y1 Y2 X3] +
0.044750144015351656 [Y0 X1 X2 Y3] +
-0.044750144015351656 [Y0 Y1 X2 X3] +
0.17771287465139907 [Z0] +
0.17059738328801052 [Z0 Z1] +
0.12293305056183809 [Z0 Z2] +
0.16768319457718972 [Z0 Z3] +
0.1777128746513991 [Z1] +
0.16768319457718972 [Z1 Z2] +
0.12293305056183809 [Z1 Z3] +
-0.24274280513140498 [Z2] +
0.17627640804319616 [Z2 Z3] +
-0.24274280513140498 [Z3]


## Quantum computing applied to Chemistry


### Fermion-to-Qubit Transformation

Lastly, the Chemistry (fermionic) problem has to be mapped onto a (qubit) problem that can be modelled using a quantum computer

E.g. Jordan-Wigner transformation:

$$\text{Annihilation, } \hat{a}_p \rightarrow \hat{Z}^{\otimes p} \otimes \frac{1}{2} (\hat{X} + i\hat{Y}) \otimes 1^{\otimes N_{qubits} -p-1}$$

$$\text{Creation, } \hat{a}_p^\dagger \rightarrow \hat{Z}^{\otimes p} \otimes \frac{1}{2} (\hat{X} - i\hat{Y}) \otimes 1^{\otimes N_{qubits} -i-1}$$

Note: In this mapping, each molecular orbital has a one-to-one mapping to a qubit, i.e. the $Z$-measurement of a qubit gives the occupancy of its associated molecular orbital directly.

In [ ]:
# Apply the Jordan-Wigner transformation to the molecular Hamiltonian
jw_mol_hamiltonian = openfermion.jordan_wigner(fermionic_hamiltonian)
print(jw_mol_hamiltonian)

### Measurements to calculate the energy expectation value

- To get the energy of our $H_2$ molecule:
    - Need to measure the terms in the above cell, such as $0.1771\dots Z_0$ and $0.1705\dots Z_0 Z_1$
    - For X/Y measurements:
        - Basis rotation gates have to be applied before measuring the output of the circuit
- Because of errors in running the quantum circuit:
    - Measurement of each Pauli string has to be repeated numerous times
- Expectation value of a Pauli string:
    - Average value over all measurements
- Total molecular energy:
    - Sum of expectation values of all Pauli strings defining the qubit molecular Hamiltonian

In [5]:
from qibo import models, gates

# from qibochem.measurement.expectation import pauli_expectation_shots, circuit_expectation_shots

In [6]:
# Example: the 0.1777 Z0 term for H2

# First, we build a basic quantum circuit with 4 (= number of spin-orbitals, nso) qubits
circuit = models.Circuit(h2.nso)
print(circuit.draw())

q0: ─
q1: ─
q2: ─
q3: ─


In the Jordan-Wigner mapping, each qubit represents the occupancy of a molecular spin-orbital.
The empty circuit with no gates is then simply just the vacuum state.
Despite that, we can still obtain the expectation value of a Pauli string for this simple circuit, as shown below.

In [10]:
from qibochem.measurement.expectation import expectation

from qibochem.driver.hamiltonian import symbolic_hamiltonian

In [11]:
circuit = models.Circuit(h2.nso)
circuit.add(gates.M(0)) # Add a measurement gate to measure Z
print(circuit.draw())

# Define the Z0 QubitOperator  
z0_qubit_operator = openfermion.QubitOperator('Z0', 0.1777)
print(f"\nTerm: {z0_qubit_operator}\n")

# The pauli_expectation_shots(circuit, nshots) helper function runs and measures the output of circuit nshots times
# Since we're looking at the Z0 term, there's no need to apply any basis rotation gates before measurement
z0_expectation_value = expectation(circuit, symbolic_hamiltonian(z0_qubit_operator), from_samples=True, n_shots=100)
print(f"Expectation value: {z0_expectation_value}")

[Qibo 0.2.2|INFO|2023-11-23 10:16:40]: Using numpy backend on /CPU:0


q0: ─M─
q1: ───
q2: ───
q3: ───

Term: 0.1777 [Z0]



ValueError: axes don't match array

Note: pauli_expectation_shots just gives the measurement directly, which is just equal to 1.0 for a circuit with no gates applied

In [ ]:
# The circuit_expectation_shots(circuit, QubitOperator, nshots) helper function can be used to get the expectation value
# of a QubitOperator, including its coefficient, directly

circuit = models.Circuit(h2.nso)

circuit_expectation = circuit_expectation_shots(circuit, z0_qubit_operator, 100)
print(f"Expectation value: {circuit_expectation}")

### Simulated quantum circuits

- Since our simulated quantum circuit doesn't have any noise, the expectation value of the Pauli string is exactly 0.1777.
- Furthermore, since we're using a simulated quantum circuit here, we can obtain the exact state of the 'qubit wave function' for the circuit
    - The state vector of the circuit can be used with the qubit Hamiltonian directly to calculate the expectation value of a Pauli string, and by extension, the qubit molecular Hamiltonian

In [12]:
# The same 0.1777 Z0 term, using the circuit state vector:
# Note: We need to broadcast the SymbolicHamiltonian using I (I as in identity) terms to match 4 qubits
# We use qibo.symbols here because openfermion.QubitOperator doesn't have I
from qibo.symbols import I, Z
from qibo.hamiltonians import SymbolicHamiltonian

# The broadcasted Z_0 term using qibo.symbol
z0_qubit_operator_broadcasted = 0.1777*Z(0)*I(1)*I(2)*I(3)
# Convert it to a Qibo SymbolicHamiltonian
z0_symbolic = SymbolicHamiltonian(z0_qubit_operator_broadcasted)

# Build and run the simulated circuit to obtain its state vector
circuit = models.Circuit(h2.nso)
circuit_result = circuit(nshots=1)
circuit_state = circuit_result.state()
# Calculate the expectation value using the state vector
z0_expectation_value = z0_symbolic.expectation(circuit_state)

print(f"Expectation value: {z0_expectation_value}")

Expectation value: 0.1777


In [15]:
# Note: Helper function in Molecule class for expectation values
# TODO: Might change in next version of Qibo (0.1.12)

# Using the broadcasted SymbolicHamiltonian
circuit = models.Circuit(h2.nso)
print(f"Expectation value: {expectation(circuit, h2.hamiltonian())}")

Expectation value: 0.7559674441714287


Going forward, we will just use the expectation value of the molecular Hamiltonian, obtained using the simulated state vector, for convenience.

In [28]:
# Example: Electronic energy of the vacuum state
circuit = models.Circuit(h2.nso)

# Get the molecular Hamiltonian, and convert it to a SymbolicHamiltonian
hamiltonian = h2.hamiltonian()

print(f" Electronic energy of vacuum state: {expectation(circuit, hamiltonian)}")

# Since there are no electrons, the electronic energy just consists of the nuclear repulsion energy
print(f"(Same as) Nuclear repulsion energy: {h2.e_nuc}")

 Electronic energy of vacuum state: 0.7559674441714287
(Same as) Nuclear repulsion energy: 0.7559674441714287


## VQE: Ansatz representing the molecular wave function

We have shown above how to calculate the molecular electronic energy from a quantum circuit.
The next step is to use a parametrized quantum circuit to model the electronic wave function of the molecule, i.e. the circuit ansatz.
The aim of VQE is thus to minimise the electronic energy with respect to the parameters of the circuit ansatz.

Here, we will use the [hardware-efficient ansatz](https://www.nature.com/articles/nature23879) to represent the wave function of the $H_2$ molecule.
Note: it's actually possible to use symmetry to further reduce the number of qubits needed to just 2, but we will stick to using the one-to-one Jordan-Wigner mapping of a spin-orbital to a qubit directly for clarity in this example)

In [17]:
from qibochem.ansatz.hardware_efficient import hea

In [20]:
help(hea)

Help on function hea in module qibochem.ansatz.hardware_efficient:

hea(n_layers, n_qubits, parameter_gates=['RY', 'RZ'], coupling_gates='CZ')
    Builds the generalized hardware-efficient ansatz, in which the rotation and entangling gates used can be
    chosen by the user
    
    Args:
        n_layers: Number of layers of rotation and entangling gates
        n_qubits: Number of qubits in the quantum circuit
        parameter_gates: List of single-qubit rotation gates to be used in the ansatz. The gates should be given as
            strings representing valid ``Qibo`` one-qubit gates. Default: ``["RY", "RZ"]``
        coupling_gates: String representing the two-qubit entangling gate to be used in the ansatz; should be a
            valid two-qubit ``Qibo`` gate. Default: ``"CZ"``
    
    Returns:
        List of gates corresponding to the hardware-efficient ansatz



In [30]:
# Get the list of quantum gates representing the ansatz
gate_list = hea(n_layers=1, n_qubits=h2.nso, coupling_gates='CNOT') # 1 layer is sufficient

# Build a quantum circuit and add the gates from gate_list to it
circuit = models.Circuit(h2.nso)
circuit.add(gate for gate in gate_list)
print(circuit.draw())

q0: ─RY─RZ─o─────X─
q1: ─RY─RZ─X─o───|─
q2: ─RY─RZ───X─o─|─
q3: ─RY─RZ─────X─o─


In [33]:
# Get the number of paramerized gates
n_param_gates = len(circuit.get_parameters())

# Create the VQE model
symbolic_hamiltonian = h2.hamiltonian()
vqe = models.VQE(circuit, symbolic_hamiltonian)

# Optimize starting from a random guess for the variational parameters
initial_parameters = np.random.uniform(0, 2*np.pi,
                                        n_param_gates)
best, params, extra = vqe.minimize(initial_parameters)# method='BFGS', compile=False) 

In [34]:
print("Results:")
print(f"{' ':>9}VQE energy: {best}\n")

print(f"Classical HF energy: {h2.e_hf}")
# Exact groundstate energy of H2 as a reference
print(f"{' ':>5}Exact solution: {symbolic_hamiltonian.eigenvalues()[0]}")

[Qibo 0.2.2|WARNING|2023-11-23 10:49:23]: Calculating the dense form of a symbolic Hamiltonian. This operation is memory inefficient.


Results:
         VQE energy: -1.1361894540659219

Classical HF energy: -1.11734903499028
     Exact solution: -1.1361894540659216


Notes:
- The first reference result, the classical HF energy, is the basic starting point for most classical computational chemistry calculations.
    - To outperform classical computational chemistry, the energy from the quantum circuit should be lower than this value
    - However, depending on the initial set of parameters and the classical optimizer, one might occasionally reach this result as a local minimum
- Of course, ideally, the VQE process manages to find the second reference result, the exact solution from diagonalizing the molecular Hamiltonian exactly